[32mINFO    [0m custom_logger:test_login.py:112 ************ test_login_positive2 STARTED ************
[1m[31mERROR   [0m custom_logger:test_login.py:136 ************ test_login_positive2 FAILED ************